version: '3.3'
services:
  redis:
    container_name: redis-rchat-webhook
    command: redis-server
    build:
      context: .
      dockerfile: docker/Dockerfile-Redis
    expose:
      - 6379
    ports:
      - 6382:6379

  rchat_webhook:
    image: rchat-webhook
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    restart: unless-stopped
    ports: 
      - "9091:3000"
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        labels: "rchat_webhook"
        env: "os"
    depends_on:
      - redis 
